name: Tests

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - main
      - developing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run smoke tests
        run: vendor/bin/phpunit --testsuite=Smoke

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite=Unit

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite=Integration

